  #!/bin/bash
  #this is to clean up a centos7 server for use as a production vm template
  #created using 
  #http://everything-virtual.com/2016/05/06/creating-a-centos-7-2-vmware-gold-template/

#stop loging data

service rsyslog stop 
service auditd stop

#get rid of data that was generated by me

/bin/package-cleanup –oldkernels –count=1
/usr/bin/yum clean all
logrotate -f /etc/logrotate.conf 
rm -f /var/log/*-???????? /var/log/*.gz 
rm -f /var/log/dmesg.old 
rm -rf /var/log/anaconda 
cat /dev/null > /var/log/audit/audit.log 
cat /dev/null > /var/log/wtmp 
cat /dev/null > /var/log/lastlog 
cat /dev/null > /var/log/grubby
