#!/bin/bash
#
#disable control-alt-del
#
#

#################################################
###
#    Cent OS 
# 
#

function centos6 {
echo "exec /usr/bin/logger -p authpriv.notice -t init "Ctrl-Alt-Del was pressed and ignored"" > /etc/init/control-alt-delete.override
}


###################
clear

echo -e "This script will disable control-alt-del on verious operating systems.\nthis script will need sudo\n"
read -p "[press any key]:"

cat /etc/*release

echo -e "what version of linux are you using (0. exit, 1. centos 6.x) \n [enter a number]:"
read -p " " input 

case $input in 
  1)
    centos6
    ;;
  0)
    echo "exiting"
    exit 1
    ;;
  *)
    echo "bad number"
    ;;
esac


